# Introduction to Pandas Lab

Complete the following set of exercises to solidify your knowledge of Pandas fundamentals.

### 1. Import Numpy and Pandas and alias them to `np` and `pd` respectively.

In [1]:
import pandas as pd
import numpy as np

### 2. Create a Pandas Series containing the elements of the list below.

In [2]:
lst = [5.7, 75.2, 74.4, 84.0, 66.5, 66.3, 55.8, 75.7, 29.1, 43.7]

In [4]:
# your code here
pd_ser = pd.Series(lst)
pd_ser

0     5.7
1    75.2
2    74.4
3    84.0
4    66.5
5    66.3
6    55.8
7    75.7
8    29.1
9    43.7
dtype: float64

### 3. Use indexing to return the third value in the Series above.

*Hint: Remember that indexing begins at 0.*

In [6]:
# your code here
pd_ser[2]

np.float64(74.4)

### 4. Create a Pandas DataFrame from the list of lists below. Each sublist should be represented as a row.

In [9]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

In [10]:
# your code here
df = pd.DataFrame(b)

df

      0     1     2     3     4
0  53.1  95.0  67.5  35.0  78.4
1  61.3  40.8  30.8  37.8  87.6
2  20.6  73.2  44.2  14.6  91.8
3  57.4   0.1  96.1   4.2  69.5
4  83.6  20.5  85.4  22.8  35.9
5  49.0  69.0   0.1  31.8  89.1
6  23.3  40.7  95.0  83.8  26.9
7  27.6  26.4  53.8  88.8  68.5
8  96.6  96.4  53.4  72.4  50.1
9  73.7  39.0  43.2  81.6  34.7

### 5. Rename the data frame columns based on the names in the list below.

In [34]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

scores = ["Score_1", "Score_2", "Score_3", "Score_4", "Score_5"]

In [39]:
# your code here
df_score = pd.DataFrame(b, columns=scores)
df_score

   Score_1  Score_2  Score_3  Score_4  Score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

### 6. Create a subset of this data frame that contains only the Score 1, 3, and 5 columns.

In [40]:
# your code here
df_score.iloc[:, [0,2,4]]

   Score_1  Score_3  Score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

### 7. From the original data frame, calculate the average Score_3 value.

In [44]:
# your code here
df_score.iloc[:,[2]].mean()

Score_3    56.95
dtype: float64

### 8. From the original data frame, calculate the maximum Score_4 value.

In [43]:
# your code here
df_score.iloc[:,[3]].max()

Score_4    88.8
dtype: float64

### 9. From the original data frame, calculate the median Score 2 value.

In [45]:
# your code here
df_score.iloc[:,[1]].median()

Score_2    40.75
dtype: float64

### 10. Create a Pandas DataFrame from the dictionary of product orders below.

In [47]:
orders = {'Description': ['LUNCH BAG APPLE DESIGN',
  'SET OF 60 VINTAGE LEAF CAKE CASES ',
  'RIBBON REEL STRIPES DESIGN ',
  'WORLD WAR 2 GLIDERS ASSTD DESIGNS',
  'PLAYING CARDS JUBILEE UNION JACK',
  'POPCORN HOLDER',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'PARTY BUNTING',
  'JAZZ HEARTS ADDRESS BOOK',
  'SET OF 4 SANTA PLACE SETTINGS'],
 'Quantity': [1, 24, 1, 2880, 2, 7, 1, 4, 10, 48],
 'UnitPrice': [1.65, 0.55, 1.65, 0.18, 1.25, 0.85, 11.95, 4.95, 0.19, 1.25],
 'Revenue': [1.65, 13.2, 1.65, 518.4, 2.5, 5.95, 11.95, 19.8, 1.9, 60.0]}

In [49]:
# your code here
pd_dp = pd.DataFrame(orders)
pd_dp

                          Description  Quantity  UnitPrice  Revenue
0              LUNCH BAG APPLE DESIGN         1       1.65     1.65
1  SET OF 60 VINTAGE LEAF CAKE CASES         24       0.55    13.20
2         RIBBON REEL STRIPES DESIGN          1       1.65     1.65
3   WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880       0.18   518.40
4    PLAYING CARDS JUBILEE UNION JACK         2       1.25     2.50
5                      POPCORN HOLDER         7       0.85     5.95
6      BOX OF VINTAGE ALPHABET BLOCKS         1      11.95    11.95
7                       PARTY BUNTING         4       4.95    19.80
8            JAZZ HEARTS ADDRESS BOOK        10       0.19     1.90
9       SET OF 4 SANTA PLACE SETTINGS        48       1.25    60.00

### 11. Calculate the total quantity ordered and revenue generated from these orders.

In [61]:
# your code here
total_qty = pd_dp['Quantity'].sum()
total_qty

np.int64(2978)

In [62]:
# your code here
total_revenue = pd_dp['Revenue'].sum()
total_revenue

np.float64(637.0)

### 12. Obtain the prices of the most expensive and least expensive items ordered and print the difference.

In [66]:
# your code here
unit_price_max = pd_dp['UnitPrice'].max()
unit_price_max

np.float64(11.95)

In [67]:
unit_price_min = pd_dp['UnitPrice'].min()
unit_price_min

np.float64(0.18)

In [68]:
unit_price_diff = unit_price_max - unit_price_min
unit_price_diff

np.float64(11.77)

## Let's load another dataset for more exercisesº

In [104]:
# Run this code:
admissions = pd.read_csv('../Admission_Predict.csv')

Let's evaluate the dataset by looking at the `head` function.

In [105]:
# your code here
admissions.head(10)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3.0,3.5,8.00,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.80
3,4,314,103,2,2.0,3.0,8.21,0,0.65
4,5,330,115,5,4.5,3.0,9.34,1,0.90
5,6,321,109,3,3.0,4.0,8.20,1,0.75
6,7,308,101,2,3.0,4.0,7.90,0,0.68
7,8,302,102,1,2.0,1.5,8.00,0,0.50
8,9,323,108,3,3.5,3.0,8.60,0,0.45
9,10,327,111,4,4.0,4.5,9.00,1,0.84

### 1 - Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [106]:
# your code here
admissions.isna()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
380,False,False,False,False,False,False,False,False,False
381,False,False,False,False,False,False,False,False,False
382,False,False,False,False,False,False,False,False,False
383,False,False,False,False,False,False,False,False,False
384,False,False,False,False,False,False,False,False,False

###  2 -  Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [107]:
# your code here
admissions.index

RangeIndex(start=0, stop=385, step=1)

In [108]:
admissions = admissions.set_index("Serial No.", drop=False)

In [109]:
admissions.index

RangeIndex(start=1, stop=386, step=1, name='Serial No.')

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

In [110]:
admissions = admissions.set_index(["GRE Score", "CGPA"], drop=False)
print(admissions)

                Serial No.  GRE Score  TOEFL Score  University Rating  SOP  \
GRE Score CGPA
337       9.65           1        337          118                  4  4.5
316       8.00           2        316          104                  3  3.0
322       8.67           3        322          110                  3  3.5
314       8.21           4        314          103                  2  2.0
330       9.34           5        330          115                  5  4.5
...                    ...        ...          ...                ...  ...
324       9.04         381        324          110                  3  3.5
325       9.11         382        325          107                  3  3.0
330       9.45         383        330          116                  4  5.0
312       8.78         384        312          103                  3  3.5
333       9.66         385        333          117                  4  5.0

                LOR   CGPA  Research  Chance of Admit
GRE Score CGPA
337       9.65   4.5  9.65         1              0.92
316       8.00   3.5  8.00         1              0.72
322       8.67   2.5  8.67         1              0.80
314       8.21   3.0  8.21         0              0.65
330       9.34   3.0  9.34         1              0.90
...              ...   ...       ...               ...
324       9.04   3.5  9.04         1              0.82
325       9.11   3.5  9.11         1              0.84
330       9.45   4.5  9.45         1              0.91
312       8.78   4.0  8.78         0              0.67
333       9.66   4.0  9.66         1              0.95

[385 rows x 9 columns]

In [111]:
admissions

,,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
GRE Score,CGPA,,,,,,,,,
337,9.65,1,337,118,4,4.5,4.5,9.65,1,0.92
316,8.00,2,316,104,3,3.0,3.5,8.00,1,0.72
322,8.67,3,322,110,3,3.5,2.5,8.67,1,0.80
314,8.21,4,314,103,2,2.0,3.0,8.21,0,0.65
330,9.34,5,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...,...
324,9.04,381,324,110,3,3.5,3.5,9.04,1,0.82
325,9.11,382,325,107,3,3.0,3.5,9.11,1,0.84
330,9.45,383,330,116,4,5.0,4.5,9.45,1,0.91
312,8.78,384,312,103,3,3.5,4.0,8.78,0,0.67
333,9.66,385,333,117,4,5.0,4.0,9.66,1,0.95

### 3 - In this part of the lab, we would like to test complex conditions on the entire data set at once. Let's start by finding the number of rows where the CGPA is greater than 9 and the student has performed an investigation.

In [112]:
# your code here
admissions.dropna()
filtered_admissions = admissions[(admissions['CGPA'] > 9) & (admissions['Research'] == 1)]
num_rows = len(filtered_admissions)
print(f"Number of rows where CGPA > 9 and Research == 1: {num_rows}")

Number of rows where CGPA > 9 and Research == 1: 101

### 4 - Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [114]:
# your code here
admissions.dropna()
filtered_admissions = admissions[(admissions['CGPA'] > 9) & (admissions['SOP'] < 3.5)]
print(filtered_admissions)

                Serial No.  GRE Score  TOEFL Score  University Rating  SOP  \
GRE Score CGPA
338       9.40          29        338          118                  4  3.0
327       9.02          63        327          114                  3  3.0
326       9.11         141        326          114                  3  3.0
324       9.01         218        324          111                  4  3.0
325       9.11         382        325          107                  3  3.0

                LOR   CGPA  Research  Chance of Admit
GRE Score CGPA
338       9.40   4.5  9.40         1              0.91
327       9.02   3.0  9.02         0              0.61
326       9.11   3.0  9.11         1              0.83
324       9.01   3.0  9.01         1              0.82
325       9.11   3.5  9.11         1              0.84

In [118]:
filtered_admissions["Chance of Admit "].mean()

np.float64(0.8019999999999999)